
POST http://localhost:8080/Invoice
Content-Type: application/json

{
"id":5,
"invno":"05",
"invdate":"2023-05-03",
"custname":"amar",
"stockname":"pencil",
"qty":10.0,
"uom":"nos",
"price":100.0,
"rate":5.0
 }
###

GET http://localhost:8080/Invoice

###
GET http://localhost:8080/Invoice/5

###


DELETE http://localhost:8080/Invoice/3

###

GET http://localhost:8080/hello

###

